name: Shell Commands

on: 
  workflow_dispatch:




jobs:
  test-container:
    runs-on: ubuntu-latest
    container: node:13.5.0-alpine3.10
    steps:
      - name: echos stringfd
        run: |
          node -v
          cat /etc/os-release
  test-container2:
    runs-on: ubuntu-latest
    services:
      app:
        image: node:13.5.0-alpine3.10
        ports: 
          - 3001:3000
    steps:
      - name: echo string
        run: |
          node -v
          cat /etc/os-release
      - name: using a container in a step
        uses: docker://node:13.5.0-alpine3.10
        with: 
          entrypoint: '/bin/echo'
          args: "Hello world"