name: Terraform Build

on: 
  workflow_dispatch:
  push:
    branches:
      - main



jobs:
  Terraform_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.8
      - name: Format Check
        id: fmt
        run: terraform fmt -check
      - name: Init
        id: init
        run: terraform init
      - name: Validate
        id: validate
        run: terraform validate
      
  Terraform_Plan:
    runs-on: ubuntu-latest
    if: ${{ needs.Terraform_Build.result == "success" }}
    needs: [Terraform_Build]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      
      
      

