name: Terraform Build

on: 
  workflow_dispatch:
  push:
    branches:
      - main



jobs:
  Terraform_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

