name: Shell Commands

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-container:
    runs-on: ubuntu-latest
    container: node:13.5.0-alpine3.10
    steps:
      - name: echo string
        run: |
          node -v
          cat /etc/os-release
      
  