name: Shell Commands

on: 
  workflow_dispatch:
  push:
    branches:
      - main




jobs:
  test-container:
    runs-on: ubuntu-latest
    container: node:13.5.0-alpine3.10
    steps:
      - name: echo string
        run: |
          node -v
          cat /etc/os-release
  test-container2:
    runs-on: ubuntu-latest
    services:
      app:
        image: node:13.5.0-alpine3.10
        ports: 
          - 3001:3000
    steps:
      - name: echo string
        run: |
          node -v
          cat /etc/os-release
      - name: echo string
        uses: node:13.5.0-alpine3.10
        run: |
          node -v
          cat /etc/os-release
      
  