name: Shell Commands

on: 
  workflow_dispatch:

jobs:
  run-sasdhell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hey there muffa effer"
      - name: multi line script
        run: |
          node -v
          npm -v
  run-shell-command:
    runs-on: windows-latest
    needs: [run-sasdhell-command]
    steps:
      - name: echo string
        shell: pwsh
        run: Write-Output "hey there muffa effer"
      - name: multi line script
        run: |
          node -v
          npm -v