name: Shell Commands

on: 
  push:
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echsdo "hey there muffa effer"
      - name: multi line script
        run: |
          node -v
          npm -v