name: Shell Commands

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  loop:
    strategy:
      matrix:
        test: [1,2,3]
        test2: [4,5,6]
        includes: 
          - test: 1
            test2: 7
        exclude: 
          - test: 1
            test2: 4
        
        
      fail-fast: true
      max-parallel: 2
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo ${{ matrix.test }} - ${{ matrix.test2 }} - ${{ matrix.test3 }}
      
  