name: Shell Commands

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  loop:
    strategy:
      matrix:
        test: [1,2,3]
        
        
      fail-fast: true
      max-parallel: 2
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo ${{ matrix.test }}
      
  