name: Terraform FMT check PR

on:
  pull_request:

jobs:
  Terraform-Fmt-Check: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Format Check
        id: fmt
        run: terraform fmt -check

  