name: Shell Commands

on: 
  workflow_dispatch:




jobs:
  test-container:
    runs-on: ubuntu-latest
    container: node:13.5.0-alpine3.10
    steps:
      - uses: actions/checkout@v1
      - name: Run file
        uses: docker://node:13.5.0-alpine3.10
        with:
          entrypoint: ./files/test.sh
          args: "yo B boy"
